user:
  email: text
  password_hash: text
  name: text
  kind: userkind
  created_at: timestamptz

userkind:
  - plotowner
  - auditor

plot:
  user_id:
  name: text
  position: box2d
  created_at: timestamptz

plot_audit:
  user_id:
  plot_id:
  date: date
  
measureditem:
  - temperature
  - weather
  - humidity
  - pesticide
  - picture

plot_measurement:
  plot_audit_id:
  item: measureditem
  value: json
  timestamp: timestamptz
